# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "DIRECTORS" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL);
create table "MOVIES" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"title" VARCHAR NOT NULL,"director_id" BIGINT);
alter table "MOVIES" add constraint "MOVIES_DIRECTOR_FK" foreign key("director_id") references "DIRECTORS"("id") on update NO ACTION on delete SET NULL;

# --- !Downs

alter table "MOVIES" drop constraint "MOVIES_DIRECTOR_FK";
drop table "MOVIES";
drop table "DIRECTORS";

